// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fastfood_order.Data;

#nullable disable

namespace fastfood_order.Data.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20220720134023_AddedHotdogs")]
    partial class AddedHotdogs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("fastfood_order.Entity.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmericanoHotDog")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassicHotDog")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DoubleHotDog")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtraBalonesia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtraBeef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtraCheese")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtraSausage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtraTurkey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<int>("FranchHotDog")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastInteractionAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("MeatHotDog")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepOfOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
